version: '3'
services:
  record:
    build: .
    image: sjawhar/meditation-eeg
    container_name: meditation-eeg-record
    environment:
      DISPLAY:
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - ./app:/home/muselsl/meditation_eeg
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.config/muselsl/bluetooth:/etc/bluetooth
      - ${HOME}/.config/muselsl/dbus:/etc/dbus-1
      - ${HOME}/.config/muselsl/devices:/var/lib/bluetooth
    network_mode: host
    privileged: true
    entrypoint: [python3, -m, meditation_eeg]
    command: [--duration, '20']
