version: '3'

services:

  record:
    build: .
    image: sjawhar/no-wander
    container_name: no-wander-record
    environment:
      DISPLAY:
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - ./app/src:/home/muselsl/no_wander
      - ./data:/home/muselsl/data
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.config/muselsl/bluetooth:/etc/bluetooth
      - ${HOME}/.config/muselsl/dbus:/etc/dbus-1
      - ${HOME}/.config/muselsl/devices:/var/lib/bluetooth
    network_mode: host
    privileged: true
    entrypoint: [python3, -m, no_wander, record]
    command: [--duration, '20']

  process:
    build: .
    image: sjawhar/no-wander
    container_name: no-wander-process
    volumes:
      - ./app/src:/home/muselsl/no_wander
      - ./data:/home/muselsl/data
    entrypoint: [python3, -m, no_wander, process]

  notebook:
    image: jupyter/tensorflow-notebook
    container_name: no-wander-notebook
    volumes:
      - ./app/src:/home/jovyan/work/no_wander
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
    ports:
      - 8888:8888
    command: [start.sh, jupyter, lab, --LabApp.token='']
