version: '3'

services:

  record:
    build: .
    image: sjawhar/no-wander
    container_name: no-wander-record
    environment:
      DISPLAY:
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - ./app/src:/home/muselsl/no_wander
      - ./data:/home/muselsl/data
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.config/muselsl/bluetooth:/etc/bluetooth
      - ${HOME}/.config/muselsl/dbus:/etc/dbus-1
      - ${HOME}/.config/muselsl/devices:/var/lib/bluetooth
    network_mode: host
    privileged: true
    entrypoint: [python3, -m, no_wander, record]

  process:
    build: .
    image: sjawhar/no-wander
    container_name: no-wander-process
    volumes:
      - ./app/src:/home/muselsl/no_wander
      - ./data:/home/muselsl/data
    entrypoint: [python3, -m, no_wander, process]

  train:
    build:
      context: .
      dockerfile: train.Dockerfile
    image: sjawhar/no-wander:train
    container_name: no-wander-train
    volumes:
      - ./app/src:/home/tf/no_wander
      - ./data:/home/tf/data
      - ./models:/home/tf/models
    entrypoint: [python3, -m, no_wander, train]

  notebook:
    build:
      context: .
      dockerfile: train.Dockerfile
    image: sjawhar/no-wander:train
    container_name: no-wander-notebook
    volumes:
      - ./app/src:/home/tf/no_wander
      - ./data:/home/tf/data
      - ./notebooks:/home/tf/notebooks
    ports:
      - 8888:8888
    command:
      - jupyter
      - lab
      - --LabApp.token=''
      - --ip=0.0.0.0
      - --no-browser
