version: '3.4'

services:

  record:
    build:
      context: .
      target: prod
    image: sjawhar/no-wander:record
    environment:
      DISPLAY:
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - ./data:/home/muselsl/data
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.config/muselsl/bluetooth:/etc/bluetooth
      - ~/.config/muselsl/dbus:/etc/dbus-1
      - ~/.config/muselsl/devices:/var/lib/bluetooth
    network_mode: host
    privileged: true
    entrypoint: [python3, -m, no_wander, record]

  process:
    build:
      context: .
      target: prod
    image: sjawhar/no-wander:record
    volumes:
      - ./no_wander:/opt/no_wander/no_wander
      - ./data:/home/muselsl/data
    entrypoint: [python3, -m, no_wander, process]

  train:
    build:
      context: .
      dockerfile: train.Dockerfile
    image: sjawhar/no-wander:train
    volumes:
      - ./no_wander:/opt/no_wander/no_wander
      - ./data:/home/tf/data
      - ./models:/home/tf/models
    entrypoint: [python3, -m, no_wander, train]

  notebook:
    build:
      context: .
      dockerfile: train.Dockerfile
    image: sjawhar/no-wander:train
    volumes:
      - ./no_wander:/opt/no_wander/no_wander
      - ./data:/home/tf/data
      - ./models:/home/tf/models
      - ./notebooks:/home/tf/notebooks
    ports:
      - 8888:8888
    command:
      - jupyter
      - lab
      - --LabApp.token=''
      - --ip=0.0.0.0
      - --no-browser
