from pathlib import Path

COL_MARKER_PREFIX = "Marker"
COL_MARKER_DEFAULT = f"{COL_MARKER_PREFIX}0"
COL_RIGHT_AUX = "Right AUX"

DATASET_TEST = "test"
DATASET_TRAIN = "train"
DATASET_VAL = "val"

DIR_ASSETS = (Path(__file__).parent / "assets").resolve()
DIR_DATA_DEFAULT = Path.cwd() / "data"
DIR_EPOCHS = "epochs"
DIR_FAILED = "failed"
DIR_INPUT = "input"
DIR_PROCESSED = "processed"
DIR_SUBJECT_PREFIX = "subject_"
DIR_TEST = "test"

EVENT_RECORD_CHUNK_START = "EVENT_RECORD_CHUNK_START"
EVENT_SESSION_END = "EVENT_SESSION_END"
EVENT_STREAMING_ERROR = "EVENT_STREAMING_ERROR"
EVENT_STREAMING_RESTARTED = "EVENT_STREAMING_RESTARTED"

MARKER_PROBE = -2
MARKER_SYNC = -1
MARKER_USER_FOCUS = 2
MARKER_USER_RECOVER = 1

PREPROCESS_EXTRACT_EEG = "PREPROCESS_EXTRACT_EEG"
PREPROCESS_MATCH = "PREPROCESS_MATCH"
PREPROCESS_NONE = "PREPROCESS_NONE"
PREPROCESS_NORMALIZE = "PREPROCESS_NORMALIZE"

SAMPLE_RATE = 256

SOURCE_ACC = "ACC"
SOURCE_EEG = "EEG"
SOURCE_GYRO = "GYRO"
SOURCE_PPG = "PPG"
