from pathlib import Path

DIR_DATA = Path('data')
DIR_FAILED = DIR_DATA / 'failed'
DIR_INPUT = DIR_DATA / 'input'
DIR_OUTPUT = DIR_DATA / 'output'
DIR_PROCESSED = DIR_DATA / 'processed'
DIR_TEST = DIR_DATA / 'test'

EVENT_RECORD_CHUNK_START = 'EVENT_RECORD_CHUNK_START'
EVENT_SESSION_END = 'EVENT_SESSION_END'
EVENT_STREAMING_ERROR = 'EVENT_STREAMING_ERROR'
EVENT_STREAMING_RESTARTED = 'EVENT_STREAMING_RESTARTED'

PACKAGE_NAME = 'meditation_eeg'
