from pathlib import Path

DIR_DATA_DEFAULT = Path(__file__).parent / 'data'
DIR_FAILED = 'failed'
DIR_INPUT = 'input'
DIR_OUTPUT = 'output'
DIR_PROCESSED = 'processed'
DIR_TEST = 'test'

EVENT_RECORD_CHUNK_START = 'EVENT_RECORD_CHUNK_START'
EVENT_SESSION_END = 'EVENT_SESSION_END'
EVENT_STREAMING_ERROR = 'EVENT_STREAMING_ERROR'
EVENT_STREAMING_RESTARTED = 'EVENT_STREAMING_RESTARTED'

PACKAGE_NAME = 'no_wander'
