version: 2
workflows:
  lstm-1l-64-normalize:
    steps:
      - name: lstm-1l-64-normalize
        command: experiment.run_single_node
        paramsFile: .ps_project/lstm-1l-64-normalize.yaml
  lstm-2l-32-64-features:
    steps:
      - name: lstm-2l-32-64-features
        command: experiment.run_single_node
        paramsFile: .ps_project/lstm-2l-32-64-features.yaml
