version: 2
workflows:
  lstm:
    steps:
      - name: lstm
        command: experiment.run_single_node
        paramsFile: .ps_project/lstm.yaml
  lstm-cnn-s1:
    steps:
      - name: lstm-cnn-s1
        command: experiment.run_single_node
        paramsFile: .ps_project/lstm-cnn-s1.yaml
  lstm-cnn-s64:
    steps:
      - name: lstm-cnn-s64
        command: experiment.run_single_node
        paramsFile: .ps_project/lstm-cnn-s64.yaml
